name: Deploy Website

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SST Deploy
        run: bunx sst deploy --stage production
        env:
          DB_URL: ${{ secrets.DB_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          WEBSITE: ${{ secrets.WEBSITE }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          MODE: "PROD"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRAPIN_API_KEY: ${{ secrets.SCRAPIN_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          COOKD_API_KEY: ${{ secrets.COOKD_API_KEY }}
          COOKD_RESUME_SCREENER_ID: ${{ secrets.COOKD_RESUME_SCREENER_ID }}
          COOKD_SLUG_ID: ${{ secrets.COOKD_SLUG_ID }}
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
